---
title: "Haz un mapa web interactivo con tres líneas de código en R"
format: html
---

# Lo prometido es deuda...

```{r}

# install.packages("tmap")
library(tmap)
tmap_mode("view")

```

```{r}

munis_cat <- readRDS("data/munis_cat.rds") |> sf::st_simplify(dTolerance = 100)
# comarc_cat <- readRDS("data/comarc_cat.rds")
# ciudades_cat <- readRDS("data/ciudades_cat.rds")

tm_shape(munis_cat) +
        tm_polygons(fill = "AREAPOL")
#         tm_text(text = "NOM_MUNI", group = "Municipios") +
    # tm_shape(comarc_cat) +
    #     tm_polygons(fill = "AREACOMAR", group = "Comarcas")
#         tm_text(text = "NOM_COMAR", group = "Medio") +
#     tm_shape(ciudades_cat) +
#         tm_dots(group = "Comarcas", fill = "darkred") +
#         tm_text(text = "Nom", group = "Comarcas", col = "darkred") +
#     tm_group("Municipios", zoom_levels = 11:20) +
#     tm_group("Comarcas", zoom_levels = 8:10) +
#     tm_group("Medio", zoom_levels = 9:10) +
#     tm_view(set_zoom_limits = c(8, 20))

```
